project:
  type: book
  output-dir: docs

book:
  title: "Fundamental Epidemiology Study Designs"
  author: "Manh Nguyen Duc"
  date: "3/20/2025"
  sidebar: 
    collapse-level: 1
  chapters:
    - index.qmd
    - intro.qmd
    - part: Basic concepts
      chapters: 
        - epi.qmd
        - bias.qmd
        - con_effect_modification.qmd
    - part: Study designs
      chapters: 
        - cross_sectional.qmd
        - cohort.qmd 
        - case_control.qmd
        - intervention.qmd
        
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, theme.scss]

  pdf:
    documentclass: scrreprt

editor: visual

