project:
  type: book
  output-dir: docs

book:
  favicon: "images/profile.png"
  title: "Fundamental Epidemiological Study Designs"
  author: "Manh Nguyen Duc"
  date: "3/20/2025"
  sidebar: 
    collapse-level: 1
  chapters:
    - index.qmd
    - intro.qmd
    - part: Basic concepts
      chapters: 
        - epi.qmd
        - occurrence.qmd
        - measures_effect.qmd
        - bias.qmd
        - con_effect_modification.qmd
        - error.qmd
        - study_design.qmd
    - part: Study designs
      chapters: 
        - cross_sectional.qmd
        - cohort.qmd 
        - case_control.qmd
        - intervention.qmd
        - eco.qmd
        
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, theme.scss]

comments:
  giscus:
    repo: manhnguy/fund_epi

