---
title: "Cross-sectional study"
---

## Design and why do Cross-sectional study?

**Design**

In a cross-sectional study, we measure the frequency of a particular exposure(s) and / or outcome(s) in a defined population at a particular point in time. Sometimes it is called prevalence study.

In a descriptive cross-sectional study, we simply describe the frequency of the exposure(s) or outcome(s) in a defined population. 

In an analytic cross-sectional study, we simultaneously collect information on both the outcome of interest potential risk factor(s) in a defined population. We then compare the prevalence of the outcome in the people exposed to each risk factor with the prevalence in those not exposed.

**Why do Cross-sectional study?**

**Descriptive study**

- as the study measures the prevalence, it is useful for health planners who need to know the burden of specific conditions in order to plan preventive and curative services.

- some cross-sectional studies also collect data on the utilisation of preventive and curative services. it's useful for predicting health care needs and establishing health-care priorities.

- Some studies collect information about the knowledge, attitudes and practices of a population in relation to a particular health-related outcome. it's useful for the development of population-level health education campaigns.

::: callout-important

Cross-sectional studies are not suitable for describing the frequency of rare exposures or outcomes.

:::

**Analytical study**

- as the study measures the prevalence at a particular time point, it does not provide strong evidence about the causality. It can be difficult to establish the time sequence of events: the exposure may be a consequence rather than a cause of the outcome (**reverse causality**)

- We cannot use cross-sectional study to test a hypothesis. Instead, we use it to generate hypothesis. 

## Main steps in conducting a Cross-sectional study

**Step 1: Defining the study question**

**Step 2: Defining the target population selecting the study population**

Refer to [Measures of Occurrence](occurrence.qmd) section for definition of different concepts of population. Basically, the target population is the group to which we can generalise our study results, while the study population consists of the individuals we intend to include in our study. If the target population is small, we can study the entire population. However, in practice, the study population is usually a sample of the target population.

It is important to select the sample as representative of the target population, otherwise we will introduce selection bias in our study. The best way to ensure this is random sampling: Simple random sampling, Systematic sampling, Stratified sampling, Multi-stage sampling.

Most of the time, not all individuals of our target population will participate in our study even though we have tried our best. We should collect as much as possible information about those who do not participate. If there is systematic different characteristics between those who participate and those who do not, there is selection bias in our study. 

**Step 3: Collecting data**

**Step 4: Analysing data**

**Step 5: Interpreting results**

## Strength and Weakness
